spring.application.name=notesbook
# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/notedb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sher4556g@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT secret key (just for dev, in prod use env variables)
jwt.secret=yourSecretKeyyourSecretKeyyourSecretKey123
jwt.expirationMs=3600000 
  # 1 hour in ms
  spring.mvc.view.prefix=/static/
spring.mvc.view.suffix=.html
spring.web.resources.static-locations=classpath:/static/